// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-PCCnRssHstMZVS1Kj36QwbWx2Bvz0gs',
    appId: '1:197299232559:web:ad797935a7a19479ca0bda',
    messagingSenderId: '197299232559',
    projectId: 'scholar-chat-app-muhannadw',
    authDomain: 'scholar-chat-app-muhannadw.firebaseapp.com',
    storageBucket: 'scholar-chat-app-muhannadw.appspot.com',
    measurementId: 'G-8E4GMWSRHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6TN5IdXyJUk3eRWXUcd-dz_ZF-Z08oA',
    appId: '1:197299232559:android:3410770638cd7350ca0bda',
    messagingSenderId: '197299232559',
    projectId: 'scholar-chat-app-muhannadw',
    storageBucket: 'scholar-chat-app-muhannadw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUY9WYXzVEQ_vQAzXmsiV26cLEXjN54E',
    appId: '1:197299232559:ios:fdc7cd5231b4b586ca0bda',
    messagingSenderId: '197299232559',
    projectId: 'scholar-chat-app-muhannadw',
    storageBucket: 'scholar-chat-app-muhannadw.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

}